-- 在 Supabase SQL Editor 中執行此腳本
-- 如果是全新建立，執行全部
-- 如果已有 orders 表，只需執行最後一行 ALTER TABLE

CREATE TABLE IF NOT EXISTS orders (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id       TEXT UNIQUE NOT NULL,
    name           TEXT NOT NULL,
    phone          TEXT NOT NULL,
    email          TEXT,
    ticket_type    TEXT NOT NULL,
    quantity       INTEGER NOT NULL,
    total_amount   INTEGER NOT NULL,
    bank_last_five TEXT NOT NULL,
    status         TEXT NOT NULL DEFAULT '待核帳',
    seats          TEXT,
    created_at     TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE orders ENABLE ROW LEVEL SECURITY;

CREATE POLICY "allow_insert" ON orders FOR INSERT WITH CHECK (true);
CREATE POLICY "allow_select" ON orders FOR SELECT USING (true);
CREATE POLICY "allow_update" ON orders FOR UPDATE USING (true);

-- 如果表已存在，只需執行這行來新增座位欄位：
-- ALTER TABLE orders ADD COLUMN IF NOT EXISTS seats TEXT;
